"""Add media compression fields to Lesson model

Revision ID: 8dfdcab3b87f
Revises: f70a48e64349
Create Date: 2026-02-16 14:01:12.931713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfdcab3b87f'
down_revision = 'f70a48e64349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compressed_video_versions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('compressed_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('compression_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('compression_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('compression_metadata')
        batch_op.drop_column('compression_status')
        batch_op.drop_column('compressed_image')
        batch_op.drop_column('compressed_video_versions')

    # ### end Alembic commands ###
