"""Add database indexes for performance optimization

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add index on enrollments table for efficient user course lookup
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('idx_enrollments_user_id', ['user_id'])
        batch_op.create_index('idx_enrollments_course_id', ['course_id'])
    
    # Add index on course for trial queries
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('idx_course_trial_enabled', ['is_trial_enabled'])
    
    # Add index on lesson_progress for efficient progress queries
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index('idx_progress_user_id', ['user_id'])
        batch_op.create_index('idx_progress_lesson_id', ['lesson_id'])
        batch_op.create_index('idx_progress_user_lesson', ['user_id', 'lesson_id'], unique=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index('idx_progress_user_lesson', if_exists=True)
        batch_op.drop_index('idx_progress_lesson_id', if_exists=True)
        batch_op.drop_index('idx_progress_user_id', if_exists=True)
    
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('idx_course_trial_enabled', if_exists=True)
    
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('idx_enrollments_course_id', if_exists=True)
        batch_op.drop_index('idx_enrollments_user_id', if_exists=True)
    
    # ### end Alembic commands ###
