"""Add trial system fields to Course and LessonProgress models

Revision ID: a1b2c3d4e5f6
Revises: 8dfdcab3b87f
Create Date: 2026-02-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '8dfdcab3b87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add trial fields to course table
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('trial_days', sa.Integer(), nullable=False, server_default='7'))
        batch_op.add_column(sa.Column('can_cancel_anytime', sa.Boolean(), nullable=False, server_default='1'))
    
    # Add trial fields to lesson_progress table
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_cancelled', sa.Boolean(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove trial fields from lesson_progress table
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_column('trial_cancelled')
        batch_op.drop_column('trial_expires_at')
        batch_op.drop_column('trial_started_at')
    
    # Remove trial fields from course table
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('can_cancel_anytime')
        batch_op.drop_column('trial_days')
        batch_op.drop_column('is_trial_enabled')
    
    # ### end Alembic commands ###
